[Settings]
; ID found in ControlMyMonitor
TargetID=\\.\DISPLAY3\Monitor0

; Path to ControlMyMonitor executable
PathToControl=F:\Documents\Outils\Nirsoft\NirSoft\controlmymonitor.exe

; Brightness levels (0-100)
DimBrightness=5
BrightBrightness=100