name: Create Release Asset

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest # We use Windows to match your AHK environment

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip Archive
        shell: pwsh
        run: |
          Compress-Archive -Path "autoDimMonitor.ahk", "resources" -DestinationPath "autoDimMonitor.zip"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: MonitorTool.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
