name: Create Release Asset

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Zip Archive
        shell: pwsh
        run: |
          # Double check these filenames match your repo exactly!
          Compress-Archive -Path "autoDimMonitor.ahk", "resources" -DestinationPath "autoDimMonitor.zip"

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: MonitorTool.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
